# Task
runShapeICP: true
runSequenceICP: false
# ICP type
useLinearICP: false
# ICP objective(s)
usePointToPoint: false
usePointToPlane: false
useSymmetric: true
# Correspondence method (ANN / PROJ)
correspondenceMethod: ANN
# Other settings
matchingMaxDistance: 0.0003
nbOfIterations: 20