# Task
runShapeICP: true
# ICP type
useLinearICP: false
# ICP objective(s)
useSymmetric: true
# Correspondence method (ANN / PROJ)
correspondenceMethod: ANN
# Other settings
matchingMaxDistance: 0.0003
nbOfIterations: 20