# Task
runShapeICP: true
# ICP type
useLinearICP: true
# ICP objective(s)
usePointToPlane: true
# Correspondence method (NN / SHOOT)
correspondenceMethod: NN
# Other settings
matchingMaxDistance: 0.0003
nbOfIterations: 20