# Task
runSequenceICP: true
# ICP type
useLinearICP: true
# ICP objective(s)
usePointToPlane: true
# Correspondence method (ANN / PROJ)
correspondenceMethod: ANN
# Other settings
matchingMaxDistance: 0.1
nbOfIterations: 10