# Task
runShapeICP: false
runSequenceICP: true
# ICP type
useLinearICP: true
# ICP objective(s)
usePointToPoint: false
usePointToPlane: true
useSymmetric: false
# Correspondence method (ANN / PROJ)
correspondenceMethod: ANN
# Other settings
matchingMaxDistance: 0.0003
nbOfIterations: 20