# Task
runSequenceICP: true
# ICP type
useLinearICP: false
# ICP objective(s)
useSymmetric: true
# Correspondence method (NN / SHOOT)
correspondenceMethod: SHOOT
useColors: false
# Other settings
matchingMaxDistance: 0.1
nbOfIterations: 10