# Task
runSequenceICP: true
# ICP type
useLinearICP: false
# ICP objective(s)
useSymmetric: true
# Correspondence method (NN / SHOOT)
correspondenceMethod: NN
# Other settings
matchingMaxDistance: 0.1
nbOfIterations: 10

evaluateRMSENearest: true
evaluateTransforms: true
evaluateTime: true

writeMeshes: true
experimentName: room_symmetric_nonlinear_nn
dataDir: ../../Data/rgbd_dataset_freiburg1_xyz/