# Task
runSequenceICP: true
# ICP type
useLinearICP: true
# ICP objective(s)
useSymmetric: true
# Correspondence method (NN / SHOOT)
correspondenceMethod: SHOOT
# Other settings
matchingMaxDistance: 0.1
nbOfIterations: 10

evaluateRMSENearest: true
evaluateTransforms: true
evaluateTime: true

writeMeshes: true
experimentName: sequence_symmetric_linear_shot
dataDir: ../../Data/rgbd_dataset_freiburg1_xyz/