# Task
runShapeICP: true
# ICP type
useLinearICP: false
# ICP objective(s)
useSymmetric: true
# Correspondence method (NN / SHOOT)
correspondenceMethod: NN_COLORS
# Other settings
matchingMaxDistance: 5
nbOfIterations: 20

evaluateRMSENaive: true # doesn't make sense for partial
evaluateRMSENearest: true
evaluateRMSENearestPlane: true
evaluateTransforms: true
evaluateTime: true

visualize: true
writeMeshes: true
experimentName: symmetric_nonlinear_nn
dataDir: ../../Data/greyc_partial/