# Task
runShapeICP: true
# ICP type
useLinearICP: true
# ICP objective(s)
usePointToPlane: true
# Correspondence method (NN / SHOOT)
correspondenceMethod: NN
# Other settings
matchingMaxDistance: 1
nbOfIterations: 20

evaluateRMSENaive: true # doesn't make sense for partial
evaluateRMSENearest: true
evaluateRMSENearestPlane: true
evaluateTransforms: true
evaluateTime: true

visualize: true
writeMeshes: true
experimentName: plane_linear_nn
dataDir: ../../Data/greyc_debug/