# Task
runShapeICP: true
# ICP type
useLinearICP: false
# ICP objective(s)
useSymmetric: true
# Correspondence method (NN / SHOOT)
correspondenceMethod: NN
# Other settings
matchingMaxDistance: 1
nbOfIterations: 10
visualize: false

evaluate_rmse_naive: true
evaluate_rmse_nn: true
evaluate_rmse_nn_plane: true
evaluate_transforms: true